-- Generated by nwg-displays on 2026-08-26 at 00:05:14. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.0",
    position = "0x570",
    scale = 1.2
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "3840x2160@60.0",
    position = "1600x390",
    scale = 1.0,
    mirror = "eDP-1"
})
