-- Generated by nwg-displays on 2026-08-27 at 12:24:14. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1.2
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "3840x2160@60.0",
    position = "1600x0",
    scale = 1.5,
    mirror = "eDP-1"
})
